# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewCountApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewCountApp
  pod 'React', :path=> '../node_modules/react-native/react-native'
  pod 'react-native-sqlite-storage', :path=>'../node_modules/react-native-sqlite-storage'
  target 'NewCountApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewCountAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NewCountApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewCountApp-tvOS

  target 'NewCountApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
